name: nextflow_for_nextstrain CI
# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.10.0', '21.03.0-edge']
    steps:
      - uses: actions/checkout@v2
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
          python-version: 3.8
          
      - name: Fix up git URLs as per https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported
        run: |
          echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
          git config --global url."git@github.com:".insteadOf git://github.com/
            
      - name: Create Singularity container and test module installation
        run: |
          cd environments/
          singularity build --fakeroot ../nextflow_nextstrain.sif Singularity
          singularity exec ../nextflow_nextstrain.sif R --version && python --version

      - name: Create Docker container and test module installation
        run: |
          cd environments/
          docker build -t nextflow_nextstrain .
          docker exec nextflow_nextstrain R --version && python --version
          
      - name: Install Nextflow
        shell: bash -l {0}
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environments/environment.yml
          activate-environment: nf_nextstrain
          channels: conda-forge,bioconda,defaults
          mamba-version: "*"  
      - name: test conda env dependencies
        run: R --version && python --version && augur --version && mafft --version && nextstrain --version


